name: Auto run bot every day
on:
  schedule: [{cron: "0 18 * * *"}]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Run cargo run --release
  run_release:
    name: Run release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run cargo run --release
        run: cargo run --release